.\" icepatch2client.1 --
.\" Created: Thu, 15 Dec 2005 22:09:31 +0100
.\"
.TH "ICEPATCH2CLIENT" "1" "2008-05-16" "Francisco Moya" "ZeroC Ice 3.5"
.SH "NAME"
icepatch2client \- replicate the data directory of an IcePatch2 server
.SH "SYNOPSIS"
.B icepatch2client [OPTIONS]... [DIRECTORY]
.SH "DESCRIPTION"
.PP
Distributed file server client.
.PP
Full documentation of this tool is available online at
.I http://www.zeroc.com/doc/Ice\-3.5/manual/IcePatch2.46.5.html
.PP
Alternatively you may find the same information in the non\-free package zeroc\-ice\-manual.
.SH "COPYRIGHT"
This man page is Copyright (C) 2008-2010 Francisco Moya.   License  GPLv3+:  GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.PP
This  is  free  software:  you  are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
.PP
The text of GPLv3 is also available in /usr/share/common\-licenses/GPL\-3
.SH "SEE ALSO"
.PP
Please, for further information refer to
.I Distributed Programming with Ice
by Michi Henning, Mark Spruiell, et al. available as a PDF file in the non\-free package
.B zeroc\-ice\-manual
or browse it online at
.I http://www.zeroc.com/doc/Ice\-3.5/manual/
