.\" slice2php.1 --
.\" Created: Thu, 03 Jul 2011 19:09:31 +0100
.\"
.TH "SLICE2PHP" "1" "2011-07-03" "Cleto Martín" "ZeroC Ice 3.5"
.SH "NAME"
slice2php \- translate Slice to Ice for PHP
.SH "SYNOPSIS"
.B slice2php [OPTIONS]... FILES...
.SH "DESCRIPTION"
.PP
Slice to PHP compiler.
.PP
Full documentation of this tool is available online at
.I http://doc.zeroc.com/display/Ice/slice2php+Command-Line+Options
.PP
Alternatively you may find the same information in the non\-free package zeroc\-ice\-manual.
.SH "COPYRIGHT"
This man page is Copyright (C) 2011 Cleto Martín.   License  GPLv3+:  GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
.PP
This  is  free  software:  you  are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.
.PP
The text of GPLv3 is also available in /usr/share/common\-licenses/GPL\-3
.SH "SEE ALSO"
.PP
Please, for further information refer to
.I Distributed Programming with Ice
by Michi Henning, Mark Spruiell, et al. available as a PDF file in the non\-free package
.B zeroc\-ice\-manual
or browse it online at
.I http://www.zeroc.com/doc/Ice\-3.5/manual/
